# Generated by Django 6.1.1 on 2026-09-15 08:24

import django.db.models.constraints
import django.db.models.deletion
import django_immediate_fk
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DB_CASCADE, to='books.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='editor',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DB_CASCADE, to='books.editor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DB_CASCADE, to='books.publisher'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=django_immediate_fk.ForeignKeyConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], field='author', name='books_book_author_immediate'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=django_immediate_fk.ForeignKeyConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], field='editor', name='books_book_editor_deferred'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=django_immediate_fk.ForeignKeyConstraint(deferrable=None, field='publisher', name='books_book_publisher_not_deferrable'),
        ),
    ]
