# Generated by Django 6.1.1 on 2026-09-04 15:52

import django.db.models.deletion
import django_immediate_fk
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DB_CASCADE, to='books.author'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=django_immediate_fk.ImmediateDeferrableFKConstraint(field='author', name='books_book_author_immediate'),
        ),
    ]
