# Generated by Django 6.1.1 on 2026-09-07 08:23

import django.db.models.deletion
import django_immediate_fk
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author_book_books_book_author_immediate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField()),
                ('book', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DB_CASCADE, to='books.book')),
            ],
            options={
                'constraints': [django_immediate_fk.ImmediateDeferrableFKConstraint(field='book', name='books_edition_book_immediate')],
            },
        ),
    ]
