# Generated by Django 6.1.1 on 2026-09-07 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_edition'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='edition',
            name='books_edition_book_immediate',
        ),
        migrations.AlterField(
            model_name='edition',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='books.book'),
        ),
    ]
